# Generated by Django 5.2.5 on 2025-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('profile_pic', models.ImageField(upload_to='profileapp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
